sudo: required
services:
  - docker

before_install:
  - docker build -t tina/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tina/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "dockerapp"
  env: "Dockerapp-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-202181106752"
  bucket_path: "dockerapp"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
     secure: "$AWS_SECRET_KEY"